# Generated by Django 3.2.6 on 2021-11-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingstate',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingstate',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
