# Generated by Django 3.2.6 on 2021-11-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_auto_20211101_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(max_length=255, null=True)),
                ('product_type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingstate',
            name='car_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingcar'),
        ),
    ]
